# Generated by Django 3.2 on 2021-04-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('employee_team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to=None)),
                ('item_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.employee')),
                ('tech_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.techitem')),
            ],
        ),
    ]
