# Generated by Django 3.2 on 2021-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='AllottedItems',
        ),
        migrations.RenameField(
            model_name='allotteditems',
            old_name='start_date',
            new_name='issue_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
