# Generated by Django 3.2 on 2021-04-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0002_auto_20210415_0646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllottedItems',
            new_name='AllottedItem',
        ),
    ]
