# Generated by Django 3.2 on 2021-04-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_rename_allotteditems_allotteditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotteditem',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_names', to='techapp.employee'),
        ),
        migrations.AlterField(
            model_name='allotteditem',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allotteditem',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allotteditem',
            name='tech_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_items', to='techapp.techitem'),
        ),
    ]
