# Generated by Django 3.2 on 2021-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_auto_20210419_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotteditem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotteditem',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
