# Generated by Django 3.2 on 2021-04-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0005_auto_20210419_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotteditem',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='allotteditem',
            name='issue_date',
        ),
    ]
