# Generated by Django 3.2 on 2021-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0006_auto_20210419_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotteditem',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='allotteditem',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
