# Generated by Django 3.2 on 2021-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0007_auto_20210419_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotteditem',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
