# Generated by Django 3.2 on 2021-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0009_remove_allotteditem_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotteditem',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
