# Generated by Django 3.2 on 2021-04-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0011_alter_employee_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_team',
            new_name='team',
        ),
    ]
