# Generated by Django 3.2 on 2021-04-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0012_auto_20210423_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotteditem',
            name='email',
        ),
    ]
