# Generated by Django 3.2 on 2021-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0013_remove_allotteditem_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotteditem',
            name='nowdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
