# Generated by Django 3.2 on 2021-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0014_allotteditem_nowdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotteditem',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='allotteditem',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
    ]
