# Generated by Django 3.2 on 2021-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0015_auto_20210427_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
